site_name: ngntrgduc's Docs
theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link
  palette:
      # Palette toggle for light mode
    - scheme: default
      primary: cyan
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: cyan
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  logo: assets/images/logo.png
  favicon: assets/images/favicon-32x32.png

extra:
  homepage: http://ngntrgduc.github.io/
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ngntrgduc
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/nguyenduc1511  
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ngntrgduc/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: Copyright &copy; 2023 <a href="https://github.com/ngntrgduc"  target="_blank">ngntrgduc</a>